export const UPDATE_CURRENT_INDEX = "UPDATE_CURRENT_INDEX";
export const ANSWER = "ANSWER";
export const NEXT_QUESTION = "NEXT_QUESTION";
export const UNCHECKED = "UNCHECKED";
export const UPDATE_QUES_ARRAY = "UPDATE_QUES_ARRAY";
export const CHANGE_QUESTION = "CHANGE_QUESTION";
export const UPDATE_SECTION = "UPDATE_SECTION";
export const IS_VISITED = "IS_VISITED";
